apply plugin: 'com.android.library'

android {
  compileSdkVersion 35
  resourcePrefix 'ms__'

  namespace "com.jaredrummler.materialspinner"

  defaultConfig {
    minSdkVersion 22
    targetSdkVersion 35
  }
}

dependencies {
  implementation 'androidx.annotation:annotation:1.9.1'
  testImplementation 'junit:junit:4.13.2'
}
